# Server config
Server:
  Host: 127.0.0.1
  Port: 10010
  Timeout:
    Server: 30
    Read: 15
    Write: 10
    Idle: 5
# Database config
Database:
  Host: 127.0.0.1
  User: 'postgres'
  Name: 'short_url_db'
  Password: '12345678'
  Debug: true
# Redis config
Redis:
  Address: ':6379'